# Generated by Django 5.2.4 on 2025-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('place', models.CharField(max_length=180)),
                ('qualification', models.CharField(max_length=180)),
                ('phone_number', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'my_app_student',
            },
        ),
    ]
