# Generated by Django 5.2.4 on 2025-07-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_student_hobby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice', models.CharField(blank=True, choices=[('microsoft 365', 'microsoft 365'), ('Google workspace', 'Google work'), ('zoho mail', 'zoho mail'), ('professional email', 'professional email')], max_length=120)),
            ],
        ),
    ]
