# Generated by Django 5.2.4 on 2025-07-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='softwarebrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice1', models.CharField(blank=True, choices=[('microsoft', 'microsoft'), ('zoho', 'zoho'), ('wasla', 'wasla'), ('odoo', 'odoo')], max_length=120)),
            ],
        ),
    ]
