# Generated by Django 5.2.4 on 2025-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_softwarebrands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice4', models.CharField(blank=True, choices=[('aboutus', 'aboutus'), ('blog', 'blog'), ('contactus', 'contactus')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Findlocalinstallers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice2', models.CharField(blank=True, choices=[('unified communication', 'unified communication'), ('pos', 'pos'), ('security system', 'security system'), ('networking', 'networking')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ondemandservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice2', models.CharField(blank=True, choices=[('sitlock', 'sitelock'), ('ssl', 'ssl'), ('acronis', 'acronis')], max_length=120)),
            ],
        ),
    ]
