# Generated by Django 5.2.4 on 2025-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_service_delete_cloud_delete_company_delete_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice4', models.CharField(blank=True, choices=[('aboutus', 'aboutus'), ('blog', 'blog'), ('contactus', 'contactus')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice', models.CharField(blank=True, choices=[('microsoft 365', 'microsoft 365'), ('Google workspace', 'Google work'), ('zoho mail', 'zoho mail'), ('professional email', 'professional email')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Findlocalinstallers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice2', models.CharField(blank=True, choices=[('unified communication', 'unified communication'), ('pos', 'pos'), ('security system', 'security system'), ('networking', 'networking')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ondemandservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice2', models.CharField(blank=True, choices=[('sitlock', 'sitelock'), ('ssl', 'ssl'), ('acronis', 'acronis')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Softwarebrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('choice1', models.CharField(blank=True, choices=[('microsoft', 'microsoft'), ('zoho', 'zoho'), ('wasla', 'wasla'), ('odoo', 'odoo')], max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
