# Generated by Django 5.2.4 on 2025-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_cloud_company_email_findlocalinstallers_hardware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='name',
            field=models.CharField(blank=True, default='Cloud', max_length=120),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, default='Company', max_length=120),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(blank=True, default='Email', max_length=120),
        ),
        migrations.AlterField(
            model_name='findlocalinstallers',
            name='name',
            field=models.CharField(blank=True, default='Findlocalinstallers', max_length=120),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='name',
            field=models.CharField(blank=True, default='Hardware', max_length=120),
        ),
        migrations.AlterField(
            model_name='ondemandservices',
            name='name',
            field=models.CharField(blank=True, default='Ondemandservices', max_length=120),
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(blank=True, default='Security', max_length=120),
        ),
        migrations.AlterField(
            model_name='softwarebrands',
            name='name',
            field=models.CharField(blank=True, default='Softwarebrands', max_length=120),
        ),
        migrations.AlterModelTable(
            name='cloud',
            table='Cloud_table',
        ),
        migrations.AlterModelTable(
            name='company',
            table='Company_table',
        ),
        migrations.AlterModelTable(
            name='email',
            table='Email_table',
        ),
        migrations.AlterModelTable(
            name='findlocalinstallers',
            table='Findlocalinstallers_table',
        ),
        migrations.AlterModelTable(
            name='hardware',
            table='Hardware_table',
        ),
        migrations.AlterModelTable(
            name='ondemandservices',
            table='Ondemandservices_table',
        ),
        migrations.AlterModelTable(
            name='security',
            table='Security_table',
        ),
        migrations.AlterModelTable(
            name='softwarebrands',
            table='Softwarebrands_table',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student_table',
        ),
    ]
