# Generated by Django 5.2.4 on 2025-07-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_customer_products_delete_cloud_delete_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='my_app_customer',
        ),
        migrations.AlterModelTable(
            name='products',
            table='my_app_table',
        ),
    ]
